language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - RAILS_ENV=test
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/uberzeit.yml.example config/uberzeit.yml"
  - "cp .env.example .env"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec -t ~js
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
